name: Build and Publish Docker Image to GCP Artifact Registry

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

env:
  # Default values - can be overridden in workflow inputs
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  IMAGE_NAME: oncall
  REGISTRIES: |
    us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/oncall/oncall
    us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/oncall/oncall
    europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/oncall/oncall

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for proper tagging
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      
      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker --quiet
          # Configure Docker for Artifact Registry
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/oncall/oncall
            us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/oncall/oncall
            europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/oncall/oncall
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      
      - name: Create Artifact Registry repositories (if they don't exist)
        if: github.event_name != 'pull_request'
        run: |
          # Parse the registries from the environment variable
          IFS=$'\n' read -d '' -r -a registry_array <<< "${{ env.REGISTRIES }}"
          
          for registry in "${registry_array[@]}"; do
            # Extract region and repository name from registry URL
            if [[ $registry =~ ([a-z0-9-]+)-docker\.pkg\.dev/([^/]+)/([^/]+)/([^/]+) ]]; then
              region="${BASH_REMATCH[1]}"
              project="${BASH_REMATCH[2]}"
              repo_name="${BASH_REMATCH[3]}"
              image_name="${BASH_REMATCH[4]}"
              
              echo "Creating repository $repo_name in region $region for project $project"
              
              # Create the repository if it doesn't exist
              gcloud artifacts repositories create $repo_name \
                --repository-format=docker \
                --location=$region \
                --project=$project \
                --description="Docker repository for $image_name" \
                --quiet || echo "Repository $repo_name already exists or creation failed"
            fi
          done
      
      - name: Push to multiple registries
        if: github.event_name != 'pull_request'
        run: |
          # Parse the registries from the environment variable
          IFS=$'\n' read -d '' -r -a registry_array <<< "${{ env.REGISTRIES }}"
          
          # Get the tags from the metadata step
          tags="${{ steps.meta.outputs.tags }}"
          
          # Build the image once and tag it for each registry
          for registry in "${registry_array[@]}"; do
            echo "Pushing to registry: $registry"
            
            # Configure Docker for this specific region
            region=$(echo $registry | cut -d'-' -f1)
            gcloud auth configure-docker $region-docker.pkg.dev --quiet
            
            # Tag and push for each tag
            for tag in $tags; do
              # Extract just the tag name without registry prefix
              tag_name=$(echo $tag | cut -d':' -f2)
              docker tag $IMAGE_NAME:$tag_name $registry:$tag_name
              docker push $registry:$tag_name
            done
          done
      
      - name: Output image information
        if: github.event_name != 'pull_request'
        run: |
          echo "## Published Images" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          IFS=$'\n' read -d '' -r -a registry_array <<< "${{ env.REGISTRIES }}"
          tags="${{ steps.meta.outputs.tags }}"
          
          for registry in "${registry_array[@]}"; do
            echo "### $registry" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            for tag in $tags; do
              tag_name=$(echo $tag | cut -d':' -f2)
              echo "- \`$registry:$tag_name\`" >> $GITHUB_STEP_SUMMARY
            done
            echo "" >> $GITHUB_STEP_SUMMARY
          done
